title: Roboruka
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roboruka pro Robotický tábor

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed

collections:
  guides:
      output: true