title: Roboruka
author: RoboticsBrno
email: info@robotikabrno.cz
description: > # this means to ignore newlines until "baseurl:"
  Roboruka pro Robotický tábor

twitter_username: RobotikaBrno
github_username:  RoboticsBrno

sass:
    style: compressed

collections:
  guides:
      output: true

plugins:
    - jekyll-responsive-image

responsive-image:
    template: _includes/srcset-resized-fallback.html



# Google Analytics
google_analytics: UA-144089676-1
