title: Roboruka
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roboruka pro Robotický tábor

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed

collections:
  guides:
      output: true

plugins:
    - jekyll-minimagick

mini_magick:
    thumbnail:
        source: img/guides/original
        destination: thumb/img/guides
        resize: "600x400"
      
    medium:
        source: img/guides/original
        destination: img/guides/
        resize: "1500x1000"